name: Rust
on: [push, pull_request, workflow_dispatch]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        env:
          SCCACHE_WEBDAV_ENDPOINT: "https://webdav.dulic-home.net/sccache"
          SCCACHE_WEBDAV_USERNAME: "webdav"
          SCCACHE_WEBDAV_PASSWORD: ${{ secrets.WEB_DAV_PASSWORD }}
      
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        env:
          SCCACHE_WEBDAV_ENDPOINT: "https://webdav.dulic-home.net/sccache"
          SCCACHE_WEBDAV_USERNAME: "webdav"
          SCCACHE_WEBDAV_PASSWORD: ${{ secrets.WEB_DAV_PASSWORD }}
          RUSTC_WRAPPER: "sccache"
        with:
          command: check
          args: --all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        env:
          SCCACHE_WEBDAV_ENDPOINT: "https://webdav.dulic-home.net/sccache"
          SCCACHE_WEBDAV_USERNAME: "webdav"
          SCCACHE_WEBDAV_PASSWORD: ${{ secrets.WEB_DAV_PASSWORD }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        env:
          SCCACHE_WEBDAV_ENDPOINT: "https://webdav.dulic-home.net/sccache"
          SCCACHE_WEBDAV_USERNAME: "webdav"
          SCCACHE_WEBDAV_PASSWORD: ${{ secrets.WEB_DAV_PASSWORD }}
          RUSTC_WRAPPER: "sccache"
        with:
          command: test
          arg: --all-features

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        env:
          SCCACHE_WEBDAV_ENDPOINT: "https://webdav.dulic-home.net/sccache"
          SCCACHE_WEBDAV_USERNAME: "webdav"
          SCCACHE_WEBDAV_PASSWORD: ${{ secrets.WEB_DAV_PASSWORD }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        env:
          SCCACHE_WEBDAV_ENDPOINT: "https://webdav.dulic-home.net/sccache"
          SCCACHE_WEBDAV_USERNAME: "webdav"
          SCCACHE_WEBDAV_PASSWORD: ${{ secrets.WEB_DAV_PASSWORD }}
          RUSTC_WRAPPER: "sccache"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
